[phases.setup]
nixPkgs = ["python311", "google-chrome", "chromedriver"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "bash -c 'gunicorn token_server:app --bind 0.0.0.0:$PORT'"
